// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ngrok.OpenApiClient.Models;
using Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Tunnel_sessions
{
    /// <summary>
    /// Builds and executes requests for operations under \tunnel_sessions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Tunnel_sessionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.ngrok.OpenApiClient.tunnel_sessions.item collection</summary>
        /// <param name="position">a resource identifier</param>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Item.Tunnel_sessionsItemRequestBuilder"/></returns>
        public global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Item.Tunnel_sessionsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Item.Tunnel_sessionsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Tunnel_sessionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tunnel_sessions{?before_id*,filter*,limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Tunnel_sessionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tunnel_sessions{?before_id*,filter*,limit*}", rawUrl)
        {
        }
        /// <summary>
        /// List all online tunnel sessions running on this account.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.TunnelSessionList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ngrok.OpenApiClient.Models.TunnelSessionList?> GetAsync(Action<RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder.Tunnel_sessionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ngrok.OpenApiClient.Models.TunnelSessionList> GetAsync(Action<RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder.Tunnel_sessionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Ngrok.OpenApiClient.Models.TunnelSessionList>(requestInfo, global::Soenneker.Ngrok.OpenApiClient.Models.TunnelSessionList.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all online tunnel sessions running on this account.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder.Tunnel_sessionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder.Tunnel_sessionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List all online tunnel sessions running on this account.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Tunnel_sessionsRequestBuilderGetQueryParameters 
        {
            /// <summary>Expects a resource ID as its input. Returns earlier entries in the result set, sorted by ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("before_id")]
            public string? BeforeId { get; set; }
#nullable restore
#else
            [QueryParameter("before_id")]
            public string BeforeId { get; set; }
#endif
            /// <summary>A CEL expression to filter the list results. Supports logical and comparison operators to match on fields such as `id`, `metadata`, `created_at`, and more. See ngrok API Filtering for syntax and field details: https://ngrok.com/docs/api/api-filtering.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
            /// <summary>Constrains the number of results in the dataset. See the [API Overview](https://ngrok.com/docs/api/index#pagination) for details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("limit")]
            public string? Limit { get; set; }
#nullable restore
#else
            [QueryParameter("limit")]
            public string Limit { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Tunnel_sessionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder.Tunnel_sessionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
