// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ngrok.OpenApiClient.App.Sessions;
using Soenneker.Ngrok.OpenApiClient.App.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Ngrok.OpenApiClient.App
{
    /// <summary>
    /// Builds and executes requests for operations under \app
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AppRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The sessions property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.App.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.App.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.App.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.App.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.App.AppRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/app", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.App.AppRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/app", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
