// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ngrok.OpenApiClient.Models;
using Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Reserved_addrs
{
    /// <summary>
    /// Builds and executes requests for operations under \reserved_addrs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Reserved_addrsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.ngrok.OpenApiClient.reserved_addrs.item collection</summary>
        /// <param name="position">a resource identifier</param>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Item.Reserved_addrsItemRequestBuilder"/></returns>
        public global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Item.Reserved_addrsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Item.Reserved_addrsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Reserved_addrsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/reserved_addrs{?before_id*,filter*,limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Reserved_addrsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/reserved_addrs{?before_id*,filter*,limit*}", rawUrl)
        {
        }
        /// <summary>
        /// List all reserved addresses on this account.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddrList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddrList?> GetAsync(Action<RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder.Reserved_addrsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddrList> GetAsync(Action<RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder.Reserved_addrsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddrList>(requestInfo, global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddrList.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new reserved address.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddr"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddr?> PostAsync(global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddrCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddr> PostAsync(global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddrCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddr>(requestInfo, global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddr.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all reserved addresses on this account.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder.Reserved_addrsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder.Reserved_addrsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new reserved address.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddrCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Ngrok.OpenApiClient.Models.ReservedAddrCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List all reserved addresses on this account.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Reserved_addrsRequestBuilderGetQueryParameters 
        {
            /// <summary>Expects a resource ID as its input. Returns earlier entries in the result set, sorted by ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("before_id")]
            public string? BeforeId { get; set; }
#nullable restore
#else
            [QueryParameter("before_id")]
            public string BeforeId { get; set; }
#endif
            /// <summary>A CEL expression to filter the list results. Supports logical and comparison operators to match on fields such as `id`, `metadata`, `created_at`, and more. See ngrok API Filtering for syntax and field details: https://ngrok.com/docs/api/api-filtering.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
            /// <summary>Constrains the number of results in the dataset. See the [API Overview](https://ngrok.com/docs/api/index#pagination) for details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("limit")]
            public string? Limit { get; set; }
#nullable restore
#else
            [QueryParameter("limit")]
            public string Limit { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Reserved_addrsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder.Reserved_addrsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Reserved_addrsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
