// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Ngrok.OpenApiClient.Abuse_reports;
using Soenneker.Ngrok.OpenApiClient.Agent_ingresses;
using Soenneker.Ngrok.OpenApiClient.Api_keys;
using Soenneker.Ngrok.OpenApiClient.App;
using Soenneker.Ngrok.OpenApiClient.Backends;
using Soenneker.Ngrok.OpenApiClient.Bot_users;
using Soenneker.Ngrok.OpenApiClient.Certificate_authorities;
using Soenneker.Ngrok.OpenApiClient.Credentials;
using Soenneker.Ngrok.OpenApiClient.Edges;
using Soenneker.Ngrok.OpenApiClient.Endpoints;
using Soenneker.Ngrok.OpenApiClient.Event_destinations;
using Soenneker.Ngrok.OpenApiClient.Event_subscriptions;
using Soenneker.Ngrok.OpenApiClient.Ip_policies;
using Soenneker.Ngrok.OpenApiClient.Ip_policy_rules;
using Soenneker.Ngrok.OpenApiClient.Ip_restrictions;
using Soenneker.Ngrok.OpenApiClient.Reserved_addrs;
using Soenneker.Ngrok.OpenApiClient.Reserved_domains;
using Soenneker.Ngrok.OpenApiClient.Service_users;
using Soenneker.Ngrok.OpenApiClient.Ssh_certificate_authorities;
using Soenneker.Ngrok.OpenApiClient.Ssh_credentials;
using Soenneker.Ngrok.OpenApiClient.Ssh_host_certificates;
using Soenneker.Ngrok.OpenApiClient.Ssh_user_certificates;
using Soenneker.Ngrok.OpenApiClient.Tls_certificates;
using Soenneker.Ngrok.OpenApiClient.Tunnel_sessions;
using Soenneker.Ngrok.OpenApiClient.Tunnels;
using Soenneker.Ngrok.OpenApiClient.Vault_secrets;
using Soenneker.Ngrok.OpenApiClient.Vaults;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Ngrok.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NgrokOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The abuse_reports property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Abuse_reports.Abuse_reportsRequestBuilder Abuse_reports
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Abuse_reports.Abuse_reportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The agent_ingresses property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Agent_ingresses.Agent_ingressesRequestBuilder Agent_ingresses
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Agent_ingresses.Agent_ingressesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The api_keys property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Api_keys.Api_keysRequestBuilder Api_keys
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Api_keys.Api_keysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The app property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.App.AppRequestBuilder App
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.App.AppRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The backends property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Backends.BackendsRequestBuilder Backends
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Backends.BackendsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bot_users property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Bot_users.Bot_usersRequestBuilder Bot_users
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Bot_users.Bot_usersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The certificate_authorities property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Certificate_authorities.Certificate_authoritiesRequestBuilder Certificate_authorities
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Certificate_authorities.Certificate_authoritiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credentials property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Credentials.CredentialsRequestBuilder Credentials
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Credentials.CredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edges property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Edges.EdgesRequestBuilder Edges
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Edges.EdgesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The endpoints property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Endpoints.EndpointsRequestBuilder Endpoints
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Endpoints.EndpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The event_destinations property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Event_destinations.Event_destinationsRequestBuilder Event_destinations
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Event_destinations.Event_destinationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The event_subscriptions property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Event_subscriptions.Event_subscriptionsRequestBuilder Event_subscriptions
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Event_subscriptions.Event_subscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ip_policies property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Ip_policies.Ip_policiesRequestBuilder Ip_policies
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Ip_policies.Ip_policiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ip_policy_rules property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Ip_policy_rules.Ip_policy_rulesRequestBuilder Ip_policy_rules
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Ip_policy_rules.Ip_policy_rulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ip_restrictions property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Ip_restrictions.Ip_restrictionsRequestBuilder Ip_restrictions
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Ip_restrictions.Ip_restrictionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reserved_addrs property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder Reserved_addrs
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Reserved_addrs.Reserved_addrsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reserved_domains property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Reserved_domains.Reserved_domainsRequestBuilder Reserved_domains
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Reserved_domains.Reserved_domainsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The service_users property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Service_users.Service_usersRequestBuilder Service_users
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Service_users.Service_usersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ssh_certificate_authorities property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Ssh_certificate_authorities.Ssh_certificate_authoritiesRequestBuilder Ssh_certificate_authorities
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Ssh_certificate_authorities.Ssh_certificate_authoritiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ssh_credentials property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Ssh_credentials.Ssh_credentialsRequestBuilder Ssh_credentials
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Ssh_credentials.Ssh_credentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ssh_host_certificates property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Ssh_host_certificates.Ssh_host_certificatesRequestBuilder Ssh_host_certificates
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Ssh_host_certificates.Ssh_host_certificatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ssh_user_certificates property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Ssh_user_certificates.Ssh_user_certificatesRequestBuilder Ssh_user_certificates
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Ssh_user_certificates.Ssh_user_certificatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tls_certificates property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Tls_certificates.Tls_certificatesRequestBuilder Tls_certificates
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Tls_certificates.Tls_certificatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tunnel_sessions property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder Tunnel_sessions
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Tunnel_sessions.Tunnel_sessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tunnels property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Tunnels.TunnelsRequestBuilder Tunnels
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Tunnels.TunnelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The vault_secrets property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Vault_secrets.Vault_secretsRequestBuilder Vault_secrets
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Vault_secrets.Vault_secretsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The vaults property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Vaults.VaultsRequestBuilder Vaults
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Vaults.VaultsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.NgrokOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NgrokOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.ngrok.com";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
