// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentIngress : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The certificate_management_policy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertPolicy? CertificateManagementPolicy { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertPolicy CertificateManagementPolicy { get; set; }
#endif
        /// <summary>The certificate_management_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertStatus? CertificateManagementStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertStatus CertificateManagementStatus { get; set; }
#endif
        /// <summary>timestamp when the Agent Ingress was created, RFC 3339 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>human-readable description of the use of this Agent Ingress. optional, max 255 bytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>the domain that you own to be used as the base domain name to generate regional agent ingress domains.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>unique Agent Ingress resource identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>arbitrary user-defined machine-readable data of this Agent Ingress. optional, max 4096 bytes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>a list of target values to use as the values of NS records for the domain property these values will delegate control over the domain to ngrok</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NsTargets { get; set; }
#nullable restore
#else
        public List<string> NsTargets { get; set; }
#endif
        /// <summary>a list of regional agent ingress domains that are subdomains of the value of domain this value may increase over time as ngrok adds more regions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RegionDomains { get; set; }
#nullable restore
#else
        public List<string> RegionDomains { get; set; }
#endif
        /// <summary>URI to the API resource of this Agent ingress</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngress"/> and sets the default values.
        /// </summary>
        public AgentIngress()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngress"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngress CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngress();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "certificate_management_policy", n => { CertificateManagementPolicy = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertPolicy>(global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertPolicy.CreateFromDiscriminatorValue); } },
                { "certificate_management_status", n => { CertificateManagementStatus = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertStatus>(global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertStatus.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "ns_targets", n => { NsTargets = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "region_domains", n => { RegionDomains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertPolicy>("certificate_management_policy", CertificateManagementPolicy);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.AgentIngressCertStatus>("certificate_management_status", CertificateManagementStatus);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("domain", Domain);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteCollectionOfPrimitiveValues<string>("ns_targets", NsTargets);
            writer.WriteCollectionOfPrimitiveValues<string>("region_domains", RegionDomains);
            writer.WriteStringValue("uri", Uri);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
