// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EndpointResponseHeaders : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>a map of header key to header value that will be injected into the HTTP Response returned to the HTTP client</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders_add? Add { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders_add Add { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>`true` if the module will be applied to traffic, `false` to disable. default `true` if unspecified</summary>
        public bool? Enabled { get; set; }
        /// <summary>a list of header names that will be removed from the HTTP Response returned to the HTTP client</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Remove { get; set; }
#nullable restore
#else
        public List<string> Remove { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders"/> and sets the default values.
        /// </summary>
        public EndpointResponseHeaders()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add", n => { Add = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders_add>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders_add.CreateFromDiscriminatorValue); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "remove", n => { Remove = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders_add>("add", Add);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteCollectionOfPrimitiveValues<string>("remove", Remove);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
