// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EndpointOAuth : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Integer number of seconds after which ngrok guarantees it will refresh user state from the identity provider and recheck whether the user is still authorized to access the endpoint. This is the preferred tunable to use to enforce a minimum amount of time after which a revoked user will no longer be able to access the resource.</summary>
        public int? AuthCheckInterval { get; set; }
        /// <summary>the prefix of the session cookie that ngrok sets on the http client to cache authentication. default is &apos;ngrok.&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CookiePrefix { get; set; }
#nullable restore
#else
        public string CookiePrefix { get; set; }
#endif
        /// <summary>`true` if the module will be applied to traffic, `false` to disable. default `true` if unspecified</summary>
        public bool? Enabled { get; set; }
        /// <summary>Integer number of seconds of inactivity after which if the user has not accessed the endpoint, their session will time out and they will be forced to reauthenticate.</summary>
        public int? InactivityTimeout { get; set; }
        /// <summary>Integer number of seconds of the maximum duration of an authenticated session. After this period is exceeded, a user must reauthenticate.</summary>
        public int? MaximumDuration { get; set; }
        /// <summary>Do not enforce authentication on HTTP OPTIONS requests. necessary if you are supporting CORS.</summary>
        public bool? OptionsPassthrough { get; set; }
        /// <summary>The provider property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuthProvider? Provider { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuthProvider Provider { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuth"/> and sets the default values.
        /// </summary>
        public EndpointOAuth()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuth"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuth CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuth();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auth_check_interval", n => { AuthCheckInterval = n.GetIntValue(); } },
                { "cookie_prefix", n => { CookiePrefix = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "inactivity_timeout", n => { InactivityTimeout = n.GetIntValue(); } },
                { "maximum_duration", n => { MaximumDuration = n.GetIntValue(); } },
                { "options_passthrough", n => { OptionsPassthrough = n.GetBoolValue(); } },
                { "provider", n => { Provider = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuthProvider>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuthProvider.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("auth_check_interval", AuthCheckInterval);
            writer.WriteStringValue("cookie_prefix", CookiePrefix);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteIntValue("inactivity_timeout", InactivityTimeout);
            writer.WriteIntValue("maximum_duration", MaximumDuration);
            writer.WriteBoolValue("options_passthrough", OptionsPassthrough);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuthProvider>("provider", Provider);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
