// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HTTPSEdge : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>timestamp when the edge configuration was created, RFC 3339 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>human-readable description of what this edge will be used for; optional, max 255 bytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>hostports served by this edge</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Hostports { get; set; }
#nullable restore
#else
        public List<string> Hostports { get; set; }
#endif
        /// <summary>unique identifier of this edge</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>arbitrary user-defined machine-readable data of this edge; optional, max 4096 bytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>The mutual_tls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointMutualTLS? MutualTls { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointMutualTLS MutualTls { get; set; }
#endif
        /// <summary>routes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdgeRoute>? Routes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdgeRoute> Routes { get; set; }
#endif
        /// <summary>The tls_termination property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTLSTermination? TlsTermination { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTLSTermination TlsTermination { get; set; }
#endif
        /// <summary>URI of the edge API resource</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdge"/> and sets the default values.
        /// </summary>
        public HTTPSEdge()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdge"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdge CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdge();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "hostports", n => { Hostports = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "mutual_tls", n => { MutualTls = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointMutualTLS>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointMutualTLS.CreateFromDiscriminatorValue); } },
                { "routes", n => { Routes = n.GetCollectionOfObjectValues<global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdgeRoute>(global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdgeRoute.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tls_termination", n => { TlsTermination = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTLSTermination>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTLSTermination.CreateFromDiscriminatorValue); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("hostports", Hostports);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointMutualTLS>("mutual_tls", MutualTls);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdgeRoute>("routes", Routes);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTLSTermination>("tls_termination", TlsTermination);
            writer.WriteStringValue("uri", Uri);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
