// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReservedDomainCreate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of a user-uploaded TLS certificate to use for connections to targeting this domain. Optional, mutually exclusive with `certificate_management_policy`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CertificateId { get; set; }
#nullable restore
#else
        public string CertificateId { get; set; }
#endif
        /// <summary>The certificate_management_policy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainCertPolicy? CertificateManagementPolicy { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainCertPolicy CertificateManagementPolicy { get; set; }
#endif
        /// <summary>human-readable description of what this reserved domain will be used for</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>hostname of the reserved domain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>arbitrary user-defined machine-readable data of this reserved domain. Optional, max 4096 bytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>deprecated: With the launch of the ngrok Global Network domains traffic is now handled globally. This field applied only to endpoints. Note that agents may still connect to specific regions. Optional, null by default. (au, eu, ap, us, jp, in, sa)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>DNS resolver targets configured for the reserved domain, or empty for &quot;global&quot; resolution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainResolvesToEntry>? ResolvesTo { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainResolvesToEntry> ResolvesTo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainCreate"/> and sets the default values.
        /// </summary>
        public ReservedDomainCreate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "certificate_id", n => { CertificateId = n.GetStringValue(); } },
                { "certificate_management_policy", n => { CertificateManagementPolicy = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainCertPolicy>(global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainCertPolicy.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "resolves_to", n => { ResolvesTo = n.GetCollectionOfObjectValues<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainResolvesToEntry>(global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainResolvesToEntry.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("certificate_id", CertificateId);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainCertPolicy>("certificate_management_policy", CertificateManagementPolicy);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("domain", Domain);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteStringValue("region", Region);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ngrok.OpenApiClient.Models.ReservedDomainResolvesToEntry>("resolves_to", ResolvesTo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
