// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SSHUserCertificateCreate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A map of critical options included in the certificate. Only two critical options are currently defined by OpenSSH: `force-command` and `source-address`. See [the OpenSSH certificate protocol spec](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.certkeys) for additional details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_critical_options? CriticalOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_critical_options CriticalOptions { get; set; }
#endif
        /// <summary>human-readable description of this SSH User Certificate. optional, max 255 bytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>A map of extensions included in the certificate. Extensions are additional metadata that can be interpreted by the SSH server for any purpose. These can be used to permit or deny the ability to open a terminal, do port forwarding, x11 forwarding, and more. If unspecified, the certificate will include limited permissions with the following extension map: `{&quot;permit-pty&quot;: &quot;&quot;, &quot;permit-user-rc&quot;: &quot;&quot;}` OpenSSH understands a number of predefined extensions. See [the OpenSSH certificate protocol spec](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.certkeys) for additional details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_extensions? Extensions { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_extensions Extensions { get; set; }
#endif
        /// <summary>arbitrary user-defined machine-readable data of this SSH User Certificate. optional, max 4096 bytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>the list of principals included in the ssh user certificate. This is the list of usernames that the certificate holder may sign in as on a machine authorizing the signing certificate authority. Dangerously, if no principals are specified, this certificate may be used to log in as any user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Principals { get; set; }
#nullable restore
#else
        public List<string> Principals { get; set; }
#endif
        /// <summary>a public key in OpenSSH Authorized Keys format that this certificate signs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicKey { get; set; }
#nullable restore
#else
        public string PublicKey { get; set; }
#endif
        /// <summary>the ssh certificate authority that is used to sign this ssh user certificate</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SshCertificateAuthorityId { get; set; }
#nullable restore
#else
        public string SshCertificateAuthorityId { get; set; }
#endif
        /// <summary>The time when the user certificate becomes valid, in RFC 3339 format. Defaults to the current time if unspecified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ValidAfter { get; set; }
#nullable restore
#else
        public string ValidAfter { get; set; }
#endif
        /// <summary>The time when this host certificate becomes invalid, in RFC 3339 format. If unspecified, a default value of 24 hours will be used. The OpenSSH certificates RFC calls this `valid_before`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ValidUntil { get; set; }
#nullable restore
#else
        public string ValidUntil { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate"/> and sets the default values.
        /// </summary>
        public SSHUserCertificateCreate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "critical_options", n => { CriticalOptions = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_critical_options>(global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_critical_options.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "extensions", n => { Extensions = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_extensions>(global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_extensions.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "principals", n => { Principals = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "public_key", n => { PublicKey = n.GetStringValue(); } },
                { "ssh_certificate_authority_id", n => { SshCertificateAuthorityId = n.GetStringValue(); } },
                { "valid_after", n => { ValidAfter = n.GetStringValue(); } },
                { "valid_until", n => { ValidUntil = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_critical_options>("critical_options", CriticalOptions);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.SSHUserCertificateCreate_extensions>("extensions", Extensions);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteCollectionOfPrimitiveValues<string>("principals", Principals);
            writer.WriteStringValue("public_key", PublicKey);
            writer.WriteStringValue("ssh_certificate_authority_id", SshCertificateAuthorityId);
            writer.WriteStringValue("valid_after", ValidAfter);
            writer.WriteStringValue("valid_until", ValidUntil);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
