// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Endpoint : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>the bindings associated with this endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Bindings { get; set; }
#nullable restore
#else
        public List<string> Bindings { get; set; }
#endif
        /// <summary>timestamp when the endpoint was created in RFC 3339 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>user-supplied description of the associated tunnel</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref? Domain { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref Domain { get; set; }
#endif
        /// <summary>The edge property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref? Edge { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref Edge { get; set; }
#endif
        /// <summary>n/a</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Host { get; set; }
#nullable restore
#else
        public string Host { get; set; }
#endif
        /// <summary>hostport served by this endpoint (hostname:port) -&gt; soon to be deprecated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hostport { get; set; }
#nullable restore
#else
        public string Hostport { get; set; }
#endif
        /// <summary>unique endpoint resource identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>user-supplied metadata of the associated tunnel or edge object</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>user supplied name for the endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>whether the endpoint allows pooling</summary>
        public bool? PoolingEnabled { get; set; }
        /// <summary>n/a</summary>
        public int? Port { get; set; }
        /// <summary>The principal property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref? Principal { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref Principal { get; set; }
#endif
        /// <summary>protocol served by this endpoint. one of `http`, `https`, `tcp`, or `tls`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Proto { get; set; }
#nullable restore
#else
        public string Proto { get; set; }
#endif
        /// <summary>deprecated [replaced by URL]: URL of the hostport served by this endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicUrl { get; set; }
#nullable restore
#else
        public string PublicUrl { get; set; }
#endif
        /// <summary>identifier of the region this endpoint belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>n/a</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scheme { get; set; }
#nullable restore
#else
        public string Scheme { get; set; }
#endif
        /// <summary>The tcp_addr property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref? TcpAddr { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref TcpAddr { get; set; }
#endif
        /// <summary>The traffic policy attached to this endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrafficPolicy { get; set; }
#nullable restore
#else
        public string TrafficPolicy { get; set; }
#endif
        /// <summary>The tunnel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref? Tunnel { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref Tunnel { get; set; }
#endif
        /// <summary>The tunnel_session property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref? TunnelSession { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref TunnelSession { get; set; }
#endif
        /// <summary>whether the endpoint is `ephemeral` (served directly by an agent-initiated tunnel) or `edge` (served by an edge) or `cloud (represents a cloud endpoint)`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>timestamp when the endpoint was updated in RFC 3339 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>the protocol the agent uses to forward with</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpstreamProtocol { get; set; }
#nullable restore
#else
        public string UpstreamProtocol { get; set; }
#endif
        /// <summary>the local address the tunnel forwards to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpstreamUrl { get; set; }
#nullable restore
#else
        public string UpstreamUrl { get; set; }
#endif
        /// <summary>URI of the Cloud Endpoint API resource</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>the url of the endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.Endpoint"/> and sets the default values.
        /// </summary>
        public Endpoint()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.Endpoint"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ngrok.OpenApiClient.Models.Endpoint CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ngrok.OpenApiClient.Models.Endpoint();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bindings", n => { Bindings = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "domain", n => { Domain = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>(global::Soenneker.Ngrok.OpenApiClient.Models.Ref.CreateFromDiscriminatorValue); } },
                { "edge", n => { Edge = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>(global::Soenneker.Ngrok.OpenApiClient.Models.Ref.CreateFromDiscriminatorValue); } },
                { "host", n => { Host = n.GetStringValue(); } },
                { "hostport", n => { Hostport = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pooling_enabled", n => { PoolingEnabled = n.GetBoolValue(); } },
                { "port", n => { Port = n.GetIntValue(); } },
                { "principal", n => { Principal = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>(global::Soenneker.Ngrok.OpenApiClient.Models.Ref.CreateFromDiscriminatorValue); } },
                { "proto", n => { Proto = n.GetStringValue(); } },
                { "public_url", n => { PublicUrl = n.GetStringValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "scheme", n => { Scheme = n.GetStringValue(); } },
                { "tcp_addr", n => { TcpAddr = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>(global::Soenneker.Ngrok.OpenApiClient.Models.Ref.CreateFromDiscriminatorValue); } },
                { "traffic_policy", n => { TrafficPolicy = n.GetStringValue(); } },
                { "tunnel", n => { Tunnel = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>(global::Soenneker.Ngrok.OpenApiClient.Models.Ref.CreateFromDiscriminatorValue); } },
                { "tunnel_session", n => { TunnelSession = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>(global::Soenneker.Ngrok.OpenApiClient.Models.Ref.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "upstream_protocol", n => { UpstreamProtocol = n.GetStringValue(); } },
                { "upstream_url", n => { UpstreamUrl = n.GetStringValue(); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("bindings", Bindings);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>("domain", Domain);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>("edge", Edge);
            writer.WriteStringValue("host", Host);
            writer.WriteStringValue("hostport", Hostport);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("pooling_enabled", PoolingEnabled);
            writer.WriteIntValue("port", Port);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>("principal", Principal);
            writer.WriteStringValue("proto", Proto);
            writer.WriteStringValue("public_url", PublicUrl);
            writer.WriteStringValue("region", Region);
            writer.WriteStringValue("scheme", Scheme);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>("tcp_addr", TcpAddr);
            writer.WriteStringValue("traffic_policy", TrafficPolicy);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>("tunnel", Tunnel);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>("tunnel_session", TunnelSession);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("upstream_protocol", UpstreamProtocol);
            writer.WriteStringValue("upstream_url", UpstreamUrl);
            writer.WriteStringValue("uri", Uri);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
