// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HTTPSEdgeRouteUpdate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The backend property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointBackendMutate? Backend { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointBackendMutate Backend { get; set; }
#endif
        /// <summary>The circuit_breaker property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCircuitBreaker? CircuitBreaker { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCircuitBreaker CircuitBreaker { get; set; }
#endif
        /// <summary>The compression property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCompression? Compression { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCompression Compression { get; set; }
#endif
        /// <summary>human-readable description of what this edge will be used for; optional, max 255 bytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>unique identifier of this edge</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EdgeId { get; set; }
#nullable restore
#else
        public string EdgeId { get; set; }
#endif
        /// <summary>unique identifier of this edge route</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The ip_restriction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointIPPolicyMutate? IpRestriction { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointIPPolicyMutate IpRestriction { get; set; }
#endif
        /// <summary>Route selector: &quot;/blog&quot; or &quot;example.com&quot; or &quot;example.com/blog&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Match { get; set; }
#nullable restore
#else
        public string Match { get; set; }
#endif
        /// <summary>Type of match to use for this route. Valid values are &quot;exact_path&quot; and &quot;path_prefix&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MatchType { get; set; }
#nullable restore
#else
        public string MatchType { get; set; }
#endif
        /// <summary>arbitrary user-defined machine-readable data of this edge. Optional, max 4096 bytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>The oauth property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuth? Oauth { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuth Oauth { get; set; }
#endif
        /// <summary>The oidc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOIDC? Oidc { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOIDC Oidc { get; set; }
#endif
        /// <summary>The request_headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointRequestHeaders? RequestHeaders { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointRequestHeaders RequestHeaders { get; set; }
#endif
        /// <summary>The response_headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders? ResponseHeaders { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders ResponseHeaders { get; set; }
#endif
        /// <summary>The saml property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointSAMLMutate? Saml { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointSAMLMutate Saml { get; set; }
#endif
        /// <summary>The traffic_policy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTrafficPolicy? TrafficPolicy { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTrafficPolicy TrafficPolicy { get; set; }
#endif
        /// <summary>The user_agent_filter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointUserAgentFilter? UserAgentFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointUserAgentFilter UserAgentFilter { get; set; }
#endif
        /// <summary>The webhook_verification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebhookValidation? WebhookVerification { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebhookValidation WebhookVerification { get; set; }
#endif
        /// <summary>The websocket_tcp_converter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebsocketTCPConverter? WebsocketTcpConverter { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebsocketTCPConverter WebsocketTcpConverter { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdgeRouteUpdate"/> and sets the default values.
        /// </summary>
        public HTTPSEdgeRouteUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdgeRouteUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdgeRouteUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ngrok.OpenApiClient.Models.HTTPSEdgeRouteUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backend", n => { Backend = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointBackendMutate>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointBackendMutate.CreateFromDiscriminatorValue); } },
                { "circuit_breaker", n => { CircuitBreaker = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCircuitBreaker>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCircuitBreaker.CreateFromDiscriminatorValue); } },
                { "compression", n => { Compression = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCompression>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCompression.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "edge_id", n => { EdgeId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "ip_restriction", n => { IpRestriction = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointIPPolicyMutate>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointIPPolicyMutate.CreateFromDiscriminatorValue); } },
                { "match", n => { Match = n.GetStringValue(); } },
                { "match_type", n => { MatchType = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "oauth", n => { Oauth = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuth>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuth.CreateFromDiscriminatorValue); } },
                { "oidc", n => { Oidc = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOIDC>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOIDC.CreateFromDiscriminatorValue); } },
                { "request_headers", n => { RequestHeaders = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointRequestHeaders>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointRequestHeaders.CreateFromDiscriminatorValue); } },
                { "response_headers", n => { ResponseHeaders = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders.CreateFromDiscriminatorValue); } },
                { "saml", n => { Saml = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointSAMLMutate>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointSAMLMutate.CreateFromDiscriminatorValue); } },
                { "traffic_policy", n => { TrafficPolicy = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTrafficPolicy>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTrafficPolicy.CreateFromDiscriminatorValue); } },
                { "user_agent_filter", n => { UserAgentFilter = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointUserAgentFilter>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointUserAgentFilter.CreateFromDiscriminatorValue); } },
                { "webhook_verification", n => { WebhookVerification = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebhookValidation>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebhookValidation.CreateFromDiscriminatorValue); } },
                { "websocket_tcp_converter", n => { WebsocketTcpConverter = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebsocketTCPConverter>(global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebsocketTCPConverter.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointBackendMutate>("backend", Backend);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCircuitBreaker>("circuit_breaker", CircuitBreaker);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointCompression>("compression", Compression);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("edge_id", EdgeId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointIPPolicyMutate>("ip_restriction", IpRestriction);
            writer.WriteStringValue("match", Match);
            writer.WriteStringValue("match_type", MatchType);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOAuth>("oauth", Oauth);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointOIDC>("oidc", Oidc);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointRequestHeaders>("request_headers", RequestHeaders);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointResponseHeaders>("response_headers", ResponseHeaders);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointSAMLMutate>("saml", Saml);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointTrafficPolicy>("traffic_policy", TrafficPolicy);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointUserAgentFilter>("user_agent_filter", UserAgentFilter);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebhookValidation>("webhook_verification", WebhookVerification);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.EndpointWebsocketTCPConverter>("websocket_tcp_converter", WebsocketTcpConverter);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
