// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Tunnel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>tunnel group backends served by this backend tunnel</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>? Backends { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ngrok.OpenApiClient.Models.Ref> Backends { get; set; }
#endif
        /// <summary>The endpoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref? Endpoint { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref Endpoint { get; set; }
#endif
        /// <summary>upstream address the ngrok agent forwards traffic over this tunnel to. this may be expressed as a URL or a network address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForwardsTo { get; set; }
#nullable restore
#else
        public string ForwardsTo { get; set; }
#endif
        /// <summary>unique tunnel resource identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>the labels the tunnel group backends will match against, if this is a backend tunnel</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.Tunnel_labels? Labels { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.Tunnel_labels Labels { get; set; }
#endif
        /// <summary>user-supplied metadata for the tunnel defined in the ngrok configuration file. See the tunnel [metadata configuration option](https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/config#common-tunnel-configuration-properties) In API version 0, this value was instead pulled from the top-level [metadata configuration option](https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/config#metadata).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>tunnel protocol for ephemeral tunnels. one of `http`, `https`, `tcp` or `tls`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Proto { get; set; }
#nullable restore
#else
        public string Proto { get; set; }
#endif
        /// <summary>URL of the ephemeral tunnel&apos;s public endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicUrl { get; set; }
#nullable restore
#else
        public string PublicUrl { get; set; }
#endif
        /// <summary>identifier of tune region where the tunnel is running</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>timestamp when the tunnel was initiated in RFC 3339 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>The tunnel_session property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref? TunnelSession { get; set; }
#nullable restore
#else
        public global::Soenneker.Ngrok.OpenApiClient.Models.Ref TunnelSession { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.Tunnel"/> and sets the default values.
        /// </summary>
        public Tunnel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ngrok.OpenApiClient.Models.Tunnel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ngrok.OpenApiClient.Models.Tunnel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ngrok.OpenApiClient.Models.Tunnel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backends", n => { Backends = n.GetCollectionOfObjectValues<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>(global::Soenneker.Ngrok.OpenApiClient.Models.Ref.CreateFromDiscriminatorValue)?.AsList(); } },
                { "endpoint", n => { Endpoint = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>(global::Soenneker.Ngrok.OpenApiClient.Models.Ref.CreateFromDiscriminatorValue); } },
                { "forwards_to", n => { ForwardsTo = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "labels", n => { Labels = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Tunnel_labels>(global::Soenneker.Ngrok.OpenApiClient.Models.Tunnel_labels.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "proto", n => { Proto = n.GetStringValue(); } },
                { "public_url", n => { PublicUrl = n.GetStringValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "started_at", n => { StartedAt = n.GetStringValue(); } },
                { "tunnel_session", n => { TunnelSession = n.GetObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>(global::Soenneker.Ngrok.OpenApiClient.Models.Ref.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>("backends", Backends);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>("endpoint", Endpoint);
            writer.WriteStringValue("forwards_to", ForwardsTo);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Tunnel_labels>("labels", Labels);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteStringValue("proto", Proto);
            writer.WriteStringValue("public_url", PublicUrl);
            writer.WriteStringValue("region", Region);
            writer.WriteStringValue("started_at", StartedAt);
            writer.WriteObjectValue<global::Soenneker.Ngrok.OpenApiClient.Models.Ref>("tunnel_session", TunnelSession);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
