// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ngrok.OpenApiClient.Backends.Failover;
using Soenneker.Ngrok.OpenApiClient.Backends.Http_response;
using Soenneker.Ngrok.OpenApiClient.Backends.Static;
using Soenneker.Ngrok.OpenApiClient.Backends.Tunnel_group;
using Soenneker.Ngrok.OpenApiClient.Backends.Weighted;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Ngrok.OpenApiClient.Backends
{
    /// <summary>
    /// Builds and executes requests for operations under \backends
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BackendsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The failover property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Backends.Failover.FailoverRequestBuilder Failover
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Backends.Failover.FailoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The http_response property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Backends.Http_response.Http_responseRequestBuilder Http_response
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Backends.Http_response.Http_responseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The static property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Backends.Static.StaticRequestBuilder Static
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Backends.Static.StaticRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tunnel_group property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Backends.Tunnel_group.Tunnel_groupRequestBuilder Tunnel_group
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Backends.Tunnel_group.Tunnel_groupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The weighted property</summary>
        public global::Soenneker.Ngrok.OpenApiClient.Backends.Weighted.WeightedRequestBuilder Weighted
        {
            get => new global::Soenneker.Ngrok.OpenApiClient.Backends.Weighted.WeightedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Backends.BackendsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BackendsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/backends", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ngrok.OpenApiClient.Backends.BackendsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BackendsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/backends", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
